--insert into pedido values (1, 0, 0, 0, 'PN123', 'desc rota', getdate(), getdate(), getdate(), 0, 0, 'numeroCli', 'numeroAr', 'numeroColeta', 'observação', 'observaçãoFrete', 0, null, 0)
--insert into pais values (2, 'BR', 'BRASIL')
--insert into estado values (3, 'São Paulo', 'SP', 2)